//
// Created by jiri on 30.7.22.
//

#ifndef SW_PINS_H
#define SW_PINS_H
#define LEFT_FORWARDS_PIN 16
#define LEFT_BACKWARDS_PIN 17
#define LEFT_SPEED_PIN 18
#define RIGHT_FORWARDS_PIN 19
#define RIGHT_BACKWARDS_PIN 21
#define RIGHT_SPEED_PIN 22
#define FRONT_LED 23
#define WIFI_CHANNEL_SELECTOR1 25
#define WIFI_CHANNEL_SELECTOR2 26
#define WIFI_CHANNEL_SELECTOR3 27
#define READY_LED 32


#endif //SW_PINS_H
